version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - mongo_data:/data/db
    networks:
      - homestay_management_homestay-network  

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret123
    depends_on:
      - mongodb
    networks:
      - homestay_management_homestay-network  

  user_service:
    build: ./user_service
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:secret123@mongodb:27017/flight_booking?authSource=admin
    networks:
      - homestay_management_homestay-network  

  flight_service:
    build: ./flight_service
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:secret123@mongodb:27017/flight_booking?authSource=admin
    networks:
      - homestay_management_homestay-network   

  booking_service:
    build: ./booking_service
    ports:
      - "8003:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:secret123@mongodb:27017/flight_booking?authSource=admin
    networks:
      - homestay_management_homestay-network

volumes:
  mongo_data:

networks:
  homestay_management_homestay-network:
    external: true
